/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2024-03-19 11:33:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class patientProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\n");
      out.write("    <title>Patient Data App: View profile</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <section class=\"main\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/topnav.jsp", out, false);
      out.write("\n");
      out.write("        <div class=\"content\">\n");
      out.write("            <h1>View patient profile</h1><br/>\n");
      out.write("            <p><b>Patient ID:</b> ");
      out.print((String) request.getAttribute("ID"));
      out.write("</p>\n");
      out.write("            <p><b>Patient Name:</b> ");
      out.print((String) request.getAttribute("PREFIX"));
      out.write(' ');
      out.print((String) request.getAttribute("FIRST"));
      out.write(' ');
      out.print((String) request.getAttribute("LAST"));
      out.write(' ');
      out.print((String) request.getAttribute("SUFFIX"));
      out.write("</p>\n");
      out.write("            <p><b>Gender:</b> ");
      out.print((String) request.getAttribute("GENDER"));
      out.write("</p>\n");
      out.write("            <p><b>Date of birth:</b> ");
      out.print((String) request.getAttribute("BIRTHDATE"));
      out.write("</p>\n");
      out.write("            <p><b>Place of birth:</b> ");
      out.print((String) request.getAttribute("BIRTHPLACE"));
      out.write("</p>\n");
      out.write("            ");
 if (!((String) request.getAttribute("DEATHDATE")).equals("")) { 
      out.write("\n");
      out.write("                <p><b>Deathdate:</b> ");
      out.print( request.getAttribute("DEATHDATE") );
      out.write("</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <p><b>Last known address:</b> ");
      out.print((String) request.getAttribute("ADDRESS"));
      out.write(',');
      out.write(' ');
      out.print((String) request.getAttribute("CITY"));
      out.write(',');
      out.write(' ');
      out.print((String) request.getAttribute("STATE"));
      out.write(',');
      out.write(' ');
      out.print((String) request.getAttribute("ZIP"));
      out.write("</p>\n");
      out.write("            <p><b>Race:</b> ");
      out.print((String) request.getAttribute("RACE"));
      out.write("</p>\n");
      out.write("            <p><b>Ethnicity:</b> ");
      out.print((String) request.getAttribute("ETHNICITY"));
      out.write("</p>\n");
      out.write("            <p><b>Social security number:</b> ");
      out.print((String) request.getAttribute("SSN"));
      out.write("</p>\n");
      out.write("\n");
      out.write("            ");
 if (!((String) request.getAttribute("DRIVERS")).equals("")) { 
      out.write("\n");
      out.write("            <p><b>Driving licence number:</b> ");
      out.print( request.getAttribute("DRIVERS") );
      out.write("</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            ");
 if (!((String) request.getAttribute("PASSPORT")).equals("")) { 
      out.write("\n");
      out.write("            <p><b>Passport number:</b> ");
      out.print( request.getAttribute("PASSPORT") );
      out.write("</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <p><b>Marital status:</b> ");
      out.print((String) request.getAttribute("MARITAL"));
      out.write("</p>\n");
      out.write("\n");
      out.write("            ");
 if (!((String) request.getAttribute("MAIDEN")).equals("")) { 
      out.write("\n");
      out.write("            <p><b>Maiden name:</b> ");
      out.print( request.getAttribute("MAIDEN") );
      out.write("</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            <br/>\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
